# Generated by Django 6.0.2 on 2026-02-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='img/avatar'),
        ),
    ]
