# Generated by Django 6.0.2 on 2026-02-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='The icon from Bootstrap, e.g. bi bi-7-circle', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tour Category',
                'verbose_name_plural': 'Tour Categories',
            },
        ),
    ]
