# Generated by Django 6.0.2 on 2026-02-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='img/avatar.jpg', upload_to='img/avatar'),
        ),
    ]
