# Generated by Django 6.0.2 on 2026-02-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(default='Male', max_length=100, verbose_name='Gender'),
        ),
    ]
